# Generated by Django 5.1.6 on 2025-07-27 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_remove_todo_completed_remove_todo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='todo_app.todo')),
            ],
        ),
    ]
